var app = angular.module('app', []);

app.controller('MGRCtrl', function($scope) {
	$scope.blog = [
		{"title":"Pinilla en BFL", "date":"Enero 30 2015", "img":"img/eventos.jpg", "link":"https://www.google.cl/", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum, voluptas nisi incidunt quos minima mollitia iusto facere repellat quod quidem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem, modi! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde assumenda debitis, hic esse eligendi minus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, harum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, ducimus."}, 
		{"title":"Testimonio de Diana Bolocco","date":"Marzo 8 2015", "img":"img/eventos_02.jpg", "link":"https://www.google.cl/", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserunt, aperiam accusantium, iste doloremque quos nulla, quisquam autem vitae voluptatibus non voluptates suscipit ipsa esse unde ea"}, 
		{"title":"Implante de Traquea","date":"Enero 5 2015", "img":"img/eventos.jpg", "link":"https://www.google.cl/", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserunt, aperiam accusantium, iste doloremque quos nulla, quisquam autem vitae voluptatibus non voluptates suscipit ipsa esse unde ea"}, 
		{"title":"Regeneración de huesos","date":"Marzo 30 2015",  "img":"img/eventos_02.jpg", "link":"https://www.google.cl/", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserunt, aperiam accusantium, iste doloremque quos nulla, quisquam autem vitae voluptatibus non voluptates suscipit ipsa esse unde ea"}, 
		{"title":"Familia","date":"Enero 30 2015",  "img":"img/eventos.jpg", "link":"https://www.google.cl/", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserunt, aperiam accusantium, iste doloremque quos nulla, quisquam autem vitae voluptatibus non voluptates suscipit ipsa esse unde ea"}, 
		{"title":"Familia","date":"Enero 30 2015",  "img":"img/eventos_02.jpg", "link":"https://www.google.cl/", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserunt, aperiam accusantium, iste doloremque quos nulla, quisquam autem vitae voluptatibus non voluptates suscipit ipsa esse unde ea"},
		{"title":"Pinilla en BFL", "date":"Enero 30 2015", "img":"img/eventos.jpg", "link":"https://www.google.cl/", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum, voluptas nisi incidunt quos minima mollitia iusto facere repellat quod quidem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem, modi! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde assumenda debitis, hic esse eligendi minus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, harum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, ducimus."}, 
		{"title":"Testimonio de Diana Bolocco","date":"Marzo 8 2015", "img":"img/eventos_02.jpg", "link":"https://www.google.cl/", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserunt, aperiam accusantium, iste doloremque quos nulla, quisquam autem vitae voluptatibus non voluptates suscipit ipsa esse unde ea"}, 
		{"title":"Implante de Traquea","date":"Enero 5 2015", "img":"img/eventos.jpg", "link":"https://www.google.cl/", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserunt, aperiam accusantium, iste doloremque quos nulla, quisquam autem vitae voluptatibus non voluptates suscipit ipsa esse unde ea"}
	];
});