var app = angular.module('app', []);

app.controller('noticiasHomeCtrl', function($scope) {
	$scope.blog = [
		{"title":"Lorem", "date":"Enero 30 2015", "img":"img/eventos.jpg", "link":"noticiasDetalle.html", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum, voluptas nisi incidunt quos minima mollitia iusto facere repellat quod quidem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem, modi! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde assumenda debitis, hic esse eligendi minus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, harum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, ducimus."}, 
		{"title":"Lorem ipsum dolor","date":"Marzo 8 2015", "img":"img/eventos_02.jpg", "link":"noticiasDetalle.html", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserunt, aperiam accusantium, iste doloremque quos nulla, quisquam autem vitae voluptatibus non voluptates suscipit ipsa esse unde ea"}, 
		{"title":"Lorem ipsum","date":"Enero 5 2015", "img":"img/eventos.jpg", "link":"noticiasDetalle.html", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserunt, aperiam accusantium, iste doloremque quos nulla, quisquam autem vitae voluptatibus non voluptates suscipit ipsa esse unde ea"}, 
		{"title":"Lorem","date":"Marzo 30 2015",  "img":"img/eventos_02.jpg", "link":"noticiasDetalle.html", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserunt, aperiam accusantium, iste doloremque quos nulla, quisquam autem vitae voluptatibus non voluptates suscipit ipsa esse unde ea"}, 
		{"title":"Lorem ipsum dolor","date":"Enero 30 2015",  "img":"img/eventos.jpg", "link":"noticiasDetalle.html", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserunt, aperiam accusantium, iste doloremque quos nulla, quisquam autem vitae voluptatibus non voluptates suscipit ipsa esse unde ea"}, 
		{"title":"Lorem ipsum","date":"Enero 30 2015",  "img":"img/eventos_02.jpg", "link":"noticiasDetalle.html", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserunt, aperiam accusantium, iste doloremque quos nulla, quisquam autem vitae voluptatibus non voluptates suscipit ipsa esse unde ea"},
		{"title":"Lorem", "date":"Enero 30 2015", "img":"img/eventos.jpg", "link":"noticiasDetalle.html", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum, voluptas nisi incidunt quos minima mollitia iusto facere repellat quod quidem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem, modi! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde assumenda debitis, hic esse eligendi minus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, harum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, ducimus."}, 
		{"title":"Lorem ipsum","date":"Marzo 8 2015", "img":"img/eventos_02.jpg", "link":"noticiasDetalle.html", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserunt, aperiam accusantium, iste doloremque quos nulla, quisquam autem vitae voluptatibus non voluptates suscipit ipsa esse unde ea"}, 
		{"title":"Lorem ipsum dolor","date":"Enero 5 2015", "img":"img/eventos.jpg", "link":"noticiasDetalle.html", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserunt, aperiam accusantium, iste doloremque quos nulla, quisquam autem vitae voluptatibus non voluptates suscipit ipsa esse unde ea"}
	];
});


app.controller('nosotrosCtrl', function($scope) {
	$scope.nosotros = [
		{"title":"Lorem ipsum dolor", "img":"img/nosotros_cuadro.jpg", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum, voluptas nisi incidunt quos minima mollitia iusto facere repellat quod quidem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem, modi! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde assumenda debitis, hic esse eligendi minus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt"}, 
		{"title":"Lorem ipsum", "img":"img/nosotros_cuadro_02.jpg", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque"}, 
		{"title":"Lorem", "img":"img/nosotros_cuadro.jpg", "description":"Lorem ipsum dolor sit amet"}, 
		{"title":"Lorem ipsum dolor", "img":"img/nosotros_cuadro_02.jpg", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque"}, 
		{"title":"Lorem ipsum", "img":"img/nosotros_cuadro.jpg", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, "}, 
		{"title":"Lorem", "img":"img/nosotros_cuadro_02.jpg", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt tenetur voluptatum adipisci explicabo recusandae alias, hic velit laudantium doloremque reprehenderit nam eum? Aspernatur quae, eos consequatur nulla repellendus minus doloremque, esse, accusamus tempore numquam neque. Deserun"},
		{"title":"Lorem ipsum dolor", "img":"img/nosotros_cuadro.jpg", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum, voluptas nisi incidunt quos minima mollitia iusto facere repellat quod quidem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem, modi! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde assumenda debitis, hic esse eligendi minus. Lorem ipsum dol"}
	];

	$scope.equipo = [
		{"title":"Lorem ipsum dolor", "img":"img/face_01.jpg", "cargo":"Lorem ipsum dolor", "orientation": "right","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum, voluptas nisi incidunt quos minima mollitia"}, 
		{"title":"Lorem ipsum", "img":"img/face_02.jpg", "cargo":"Lorem ipsum dolor", "orientation": "right", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia nat"}, 
		{"title":"Lorem", "img":"img/face_02.jpg", "cargo":"Lorem ipsum dolor", "orientation": "left", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt "}, 
		{"title":"Lorem ipsum dolor", "img":"img/face_01.jpg", "cargo":"Lorem ipsum dolor", "orientation": "left", "description":"Lorem ipsum dolor sit amet"}, 
		{"title":"Lorem ipsum", "img":"img/face_01.jpg", "cargo":"Lorem ipsum dolor", "orientation": "right", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae"}, 
		{"title":"Lorem", "img":"img/face_02.jpg", "cargo":"Lorem ipsum dolor", "orientation": "right", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia natus placeat asperiores dolore sapiente quae similique, magni corporis commodi vitae sunt "},
		{"title":"Lorem ipsum dolor", "img":"img/face_01.jpg", "cargo":"Lorem ipsum dolor", "orientation": "left","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum, voluptas nisi incidunt quos minima mollitia"}, 
		{"title":"Lorem ipsum", "img":"img/face_02.jpg", "cargo":"Lorem ipsum dolor", "orientation": "left", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia nat"}
	];
});


app.controller('masterPlanCtrl', function($scope) {
	$scope.masterPlan = [
		{"title":"Lorem", "img":"img/eventos.jpg"},
		{"title":"Lorem ipsum", "img":"img/eventos.jpg"},
		{"title":"Lorem ipsum dolor", "img":"img/eventos.jpg"},
		{"title":"Lorem", "img":"img/eventos.jpg"},
		{"title":"Lorem ipsum", "img":"img/eventos.jpg"},
		{"title":"Lorem ipsum dolor", "img":"img/eventos.jpg"},
		{"title":"Lorem", "img":"img/eventos.jpg"},
		{"title":"Lorem ipsum", "img":"img/eventos.jpg"},
		{"title":"Lorem ipsum dolor", "img":"img/eventos.jpg"}
	];
});